[package]
name = "eck-compiler"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ir = { package = "eck-ir", path = "../ir" }
language_core = { package = "eck-core", path = "../core" }
syntax = { package = "eck-syntax", path = "../syntax" }
thiserror.workspace = true

[dev-dependencies]
measures = { package = "eck-measures", path = "../measures" }
primitives = { package = "eck-primitives", path = "../primitives" }
parser = { package = "eck-parser", path = "../parser" }
