[package]
name = "eck-double"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
language_core = { package = "eck-core", path = "../../language/core" }

[dev-dependencies]
float = { package = "eck-float", path = "../float" }
integer = { package = "eck-int", path = "../integer" }
