[package]
name = "eck-bool"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
language_core = { package = "eck-core", path = "../../language/core" }
rust_decimal.workspace = true

[dev-dependencies]
decimal = { package = "eck-decimal", path = "../decimal" }
double = { package = "eck-double", path = "../double" }
float = { package = "eck-float", path = "../float" }
integer = { package = "eck-int", path = "../integer" }
