[workspace]
resolver = "2"
members = [
  "crates/core",
  "crates/compiler",
  "crates/ir",
  "crates/parser",
  "crates/primitives",
  "crates/measures",
  "crates/runtime",
  "crates/std/*",
  "crates/cli",
  "crates/lsp",
  "crates/dialect",
  "crates/test-runner",
]

[workspace.package]
edition = "2024"
license = "MIT"
version = "0.0.1"

[workspace.dependencies]
thiserror = "2"
rust_decimal = "1.43"
regex = "1.13"
num-bigint = "0.5"

[profile.release]
lto = true
codegen-units = 1
strip = "symbols"
