[package]
name = "eck-decimal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
language_core = { package = "eck-core", path = "../../language/core" }
rust_decimal.workspace = true

[dev-dependencies]
double = { package = "eck-double", path = "../double" }
float = { package = "eck-float", path = "../float" }
